version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions:
        - php
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Design/TooManyPublicMethods:
        enabled: false
