checks:
  php: true

build:
  environment:
    php:
      version: 7.3.0
  dependencies:
    before:
      - mysql -e 'create database translatable_test;'
      - echo "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret'; \n GRANT ALL PRIVILEGES ON * . * TO 'homestead'@'localhost'; \nFLUSH PRIVILEGES; \n" | mysql -u root
  tests:
    override:
      - command: echo 1

tools:
  external_code_coverage:
    timeout: 3600
    runs: 4
